// Code generated by tools/schema-gen. DO NOT EDIT.
// Source of truth: packages/*/schema (ADR-002).

package sdk

type BackendNode struct {
	Active bool `json:"active",omitempty`
	Drain bool `json:"drain",omitempty`
	Host string `json:"host"`
	Id Ulid `json:"id"`
	Port int `json:"port"`
	Protocol string `json:"protocol",omitempty`
	SlowStart int `json:"slow_start",omitempty`
	Weight int `json:"weight",omitempty`
}

type BackendPool struct {
	ApplicationId Ulid `json:"application_id"`
	HealthMonitor HealthMonitor `json:"health_monitor",omitempty`
	Id Ulid `json:"id"`
	LbAlgorithm string `json:"lb_algorithm"`
	Name string `json:"name"`
	Nodes []BackendNode `json:"nodes"`
	Sticky bool `json:"sticky",omitempty`
	StickyCookie string `json:"sticky_cookie",omitempty`
	StickyType string `json:"sticky_type",omitempty`
}

type HealthMonitor struct {
	FailThreshold int `json:"fail_threshold"`
	HttpExpectedStatus []int `json:"http_expected_status",omitempty`
	HttpPath string `json:"http_path",omitempty`
	IntervalMs int `json:"interval_ms"`
	PassThreshold int `json:"pass_threshold"`
	TimeoutMs int `json:"timeout_ms"`
	Type string `json:"type"`
}

type Route struct {
	BackendPoolId Ulid `json:"backend_pool_id"`
	Id Ulid `json:"id"`
	Match string `json:"match"`
	Path string `json:"path"`
	Priority int `json:"priority",omitempty`
}

// Timestamp format: date-time
type Timestamp string

type TlsProfile struct {
	CertificateRef string `json:"certificate_ref",omitempty`
	Enabled bool `json:"enabled"`
	MinVersion string `json:"min_version",omitempty`
	Protocols []string `json:"protocols",omitempty`
}

// Ulid ULID, 26 char Crockford base32
// Ulid pattern: ^[0-9A-HJKMNP-TV-Z]{26}$
type Ulid string

type VirtualServer struct {
	DefaultBackendPoolId Ulid `json:"default_backend_pool_id"`
	Id Ulid `json:"id"`
	Limits VirtualServerLimits `json:"limits",omitempty`
	ListenAddr string `json:"listen_addr"`
	ListenPort int `json:"listen_port"`
	Name string `json:"name"`
	Routes []Route `json:"routes",omitempty`
	Tls TlsProfile `json:"tls"`
}

type PolicyHeaders struct {
	RequestIdHeader string `json:"request_id_header"`
	TrustedProxyHeaders []string `json:"trusted_proxy_headers"`
}

type PolicySettings struct {
	EventRetentionDays int `json:"event_retention_days"`
	LogLevel string `json:"log_level"`
}

type PolicySignature struct {
	Algorithm string `json:"algorithm"`
	KeyId string `json:"key_id"`
	Value string `json:"value"`
}

type VirtualServerLimits struct {
	MaxBodySize int `json:"max_body_size",omitempty`
	MaxHeaderSize int `json:"max_header_size",omitempty`
	MaxRequestLine int `json:"max_request_line",omitempty`
}

// Policy Declarative policy/config bundle distributed to gateways. Additive-only: unknown fields are preserved and ignored by older consumers (ADR-002 D1).
type Policy struct {
	BackendPools []BackendPool `json:"backend_pools"`
	ConfigId Ulid `json:"config_id"`
	CreatedAt Timestamp `json:"created_at"`
	CreatedBy Ulid `json:"created_by"`
	Extensions map[string]any `json:"extensions",omitempty`
	GatewayTargets []string `json:"gateway_targets",omitempty`
	Headers PolicyHeaders `json:"headers",omitempty`
	Replaces Ulid `json:"replaces",omitempty`
	SchemaVersion string `json:"schema_version"` // const: "0.1"
	Settings PolicySettings `json:"settings"`
	Signature PolicySignature `json:"signature",omitempty`
	VirtualServers []VirtualServer `json:"virtual_servers"`
}

type PolicyHeaders struct {
	RequestIdHeader string `json:"request_id_header"`
	TrustedProxyHeaders []string `json:"trusted_proxy_headers"`
}

type PolicySettings struct {
	EventRetentionDays int `json:"event_retention_days"`
	LogLevel string `json:"log_level"`
}

type PolicySignature struct {
	Algorithm string `json:"algorithm"`
	KeyId string `json:"key_id"`
	Value string `json:"value"`
}

type VirtualServerLimits struct {
	MaxBodySize int `json:"max_body_size",omitempty`
	MaxHeaderSize int `json:"max_header_size",omitempty`
	MaxRequestLine int `json:"max_request_line",omitempty`
}

// Event Structured security event record with flat fields matching the API and DB representation. Additive-only (ADR-002 D3). Events never contain request bodies, cookies, or credentials.
type Event struct {
	ApplicationId string `json:"application_id",omitempty`
	ClientIp string `json:"client_ip"` // format: ipv4
	CreatedAt Timestamp `json:"created_at"`
	DecisionAction string `json:"decision_action"`
	EventId Ulid `json:"event_id"`
	GatewayId string `json:"gateway_id",omitempty`
	Host string `json:"host",omitempty`
	Id Ulid `json:"id"`
	Masked bool `json:"masked",omitempty`
	MatchDetails []map[string]string `json:"match_details",omitempty`
	Method string `json:"method"`
	Path string `json:"path"`
	Reason string `json:"reason"`
	RequestId Ulid `json:"request_id"`
	RuleIds []string `json:"rule_ids"`
	Severity string `json:"severity"`
	Status int `json:"status"`
	Timestamp Timestamp `json:"timestamp"`
	VirtualServerId string `json:"virtual_server_id",omitempty`
}

