// Code generated by tools/schema-gen. DO NOT EDIT.
// Source of truth: packages/*/schema (ADR-002).

package sdk

// BackendNode 
type BackendNode struct {
	Active bool `json:"active,omitempty"`
	Host string `json:"host,omitempty"`
	Id Ulid `json:"id,omitempty"`
	Port int `json:"port,omitempty"`
	Weight int `json:"weight,omitempty"`
}

// BackendPool 
type BackendPool struct {
	ApplicationId Ulid `json:"application_id,omitempty"`
	HealthMonitor HealthMonitor `json:"health_monitor,omitempty"`
	Id Ulid `json:"id,omitempty"`
	LbAlgorithm string `json:"lb_algorithm,omitempty"`
	Name string `json:"name,omitempty"`
	Nodes []BackendNode `json:"nodes,omitempty"`
}

// HealthMonitor 
type HealthMonitor struct {
	FailThreshold int `json:"fail_threshold,omitempty"`
	HttpExpectedStatus []int `json:"http_expected_status,omitempty"`
	HttpPath string `json:"http_path,omitempty"`
	IntervalMs int `json:"interval_ms,omitempty"`
	PassThreshold int `json:"pass_threshold,omitempty"`
	TimeoutMs int `json:"timeout_ms,omitempty"`
	Type string `json:"type,omitempty"`
}

// Route 
type Route struct {
	BackendPoolId Ulid `json:"backend_pool_id,omitempty"`
	Id Ulid `json:"id,omitempty"`
	Match string `json:"match,omitempty"`
	Path string `json:"path,omitempty"`
	Priority int `json:"priority,omitempty"`
}

// Timestamp 
type Timestamp string

// TlsProfile 
type TlsProfile struct {
	CertificateRef string `json:"certificate_ref,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	MinVersion string `json:"min_version,omitempty"`
	Protocols []string `json:"protocols,omitempty"`
}

// Ulid ULID, 26 char Crockford base32
type Ulid string

// VirtualServer 
type VirtualServer struct {
	DefaultBackendPoolId Ulid `json:"default_backend_pool_id,omitempty"`
	Id Ulid `json:"id,omitempty"`
	Limits string `json:"limits,omitempty"`
	ListenAddr string `json:"listen_addr,omitempty"`
	ListenPort int `json:"listen_port,omitempty"`
	Name string `json:"name,omitempty"`
	Routes []Route `json:"routes,omitempty"`
	Tls TlsProfile `json:"tls,omitempty"`
}

// Client 
type Client struct {
	ForwardedFor string `json:"forwarded_for,omitempty"`
	Ip string `json:"ip,omitempty"`
	Port int `json:"port,omitempty"`
}

// Decision 
type Decision struct {
	Action string `json:"action,omitempty"`
	Reason string `json:"reason,omitempty"`
}

// Request 
type Request struct {
	BodySize int `json:"body_size,omitempty"`
	ContentType string `json:"content_type,omitempty"`
	HeadersCount int `json:"headers_count,omitempty"`
	Host string `json:"host,omitempty"`
	HttpVersion string `json:"http_version,omitempty"`
	Method string `json:"method,omitempty"`
	Path string `json:"path,omitempty"`
	Query string `json:"query,omitempty"`
}

// Response 
type Response struct {
	BackendNode string `json:"backend_node,omitempty"`
	Bytes int `json:"bytes,omitempty"`
	LatencyMs float64 `json:"latency_ms,omitempty"`
	Status int `json:"status,omitempty"`
}

