// schema-gen generates Go and TypeScript types from the JSON Schema files in
// packages/*/schema (the source of truth per ADR-002). Run via `make gen`.
//
// Usage:
//
//	go run ./tools/schema-gen
//
// This generator is intentionally simple: it supports the subset of JSON
// Schema used by the policy/event schemas (object, array, string, integer,
// number, boolean, enum, refs, formats). It does not attempt full JSON Schema
// coverage — the schemas themselves are validated independently.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type schema struct {
	Title       string             `json:"title"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
	Properties  map[string]*schema `json:"properties"`
	Items       *schema            `json:"items"`
	Ref         string             `json:"$ref"`
	Enum        []any              `json:"enum"`
	Format      string             `json:"format"`
	Defs        map[string]*schema `json:"$defs"`
}

type file struct {
	Title string             `json:"title"`
	Type  string             `json:"type"`
	Defs  map[string]*schema `json:"$defs"`
}

// emitted tracks definition names already written across schema files.
var emitted = map[string]bool{}

func main() {
	root := "."
	outDir := "packages"
	if len(os.Args) > 1 && os.Args[1] == "-out-dir" && len(os.Args) > 2 {
		outDir = os.Args[2]
	}
	inputs := []string{
		"packages/policy-schema/schema/policy-v0.json",
		"packages/event-schema/schema/event-v0.json",
	}

	var goOut bytes.Buffer
	goOut.WriteString("// Code generated by tools/schema-gen. DO NOT EDIT.\n")
	goOut.WriteString("// Source of truth: packages/*/schema (ADR-002).\n\n")
	goOut.WriteString("package sdk\n\n")

	var tsOut bytes.Buffer
	tsOut.WriteString("// Code generated by tools/schema-gen. DO NOT EDIT.\n")
	tsOut.WriteString("// Source of truth: packages/*/schema (ADR-002).\n\n")

	for _, in := range inputs {
		raw, err := os.ReadFile(filepath.Join(root, in))
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", in, err)
			os.Exit(1)
		}
		var f file
		if err := json.Unmarshal(raw, &f); err != nil {
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", in, err)
			os.Exit(1)
		}
		genSchema(f, &goOut, &tsOut)
	}

	goDir := filepath.Join(outDir, "sdk-go")
	tsDir := filepath.Join(outDir, "sdk-typescript", "src")
	if err := os.MkdirAll(goDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir sdk-go: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(tsDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir sdk-ts: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(goDir, "sdk.go"), goOut.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write sdk-go: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(tsDir, "types.ts"), tsOut.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write sdk-typescript: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("gen: wrote sdk-go/sdk.go and sdk-typescript/src/types.ts")
}

// genSchema emits types for every $def in the schema file. Definitions with
// the same name across schema files (e.g. ulid, timestamp) are emitted once.
func genSchema(f file, goOut, tsOut *bytes.Buffer) {
	// Stable ordering for deterministic output.
	names := make([]string, 0, len(f.Defs))
	for n := range f.Defs {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		if emitted[name] {
			continue
		}
		emitted[name] = true
		def := f.Defs[name]
		goType := toGoType(def, name)
		goOut.WriteString(fmt.Sprintf("// %s %s\n", toGoName(name), docLine(def.Description)))
		goOut.WriteString(fmt.Sprintf("type %s %s\n\n", toGoName(name), goType))
		tsOut.WriteString(fmt.Sprintf("export type %s = %s;\n\n", toTSName(name), toTSType(def)))
	}
}

// toGoType renders a Go type for a schema definition. Named object definitions
// become structs; simple definitions map to their primitive Go type.
func toGoType(s *schema, name string) string {
	switch {
	case s.Type == "object" || len(s.Properties) > 0:
		var b bytes.Buffer
		b.WriteString("struct {\n")
		keys := make([]string, 0, len(s.Properties))
		for k := range s.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			prop := s.Properties[k]
			tag := fmt.Sprintf("`json:\"%s\"`", k)
			if !isRequired(k, s) {
				tag = fmt.Sprintf("`json:\"%s,omitempty\"`", k)
			}
			b.WriteString(fmt.Sprintf("\t%s %s %s\n", toGoName(k), goFieldType(prop), tag))
		}
		b.WriteString("}")
		return b.String()
	case s.Ref != "":
		return toGoName(refBase(s.Ref))
	case s.Type == "array":
		return "[]" + goFieldType(s.Items)
	case s.Type == "integer":
		return "int"
	case s.Type == "number":
		return "float64"
	case s.Type == "boolean":
		return "bool"
	default:
		if len(s.Enum) > 0 {
			return "string"
		}
		return "string"
	}
}

func goFieldType(s *schema) string {
	switch {
	case s.Ref != "":
		return toGoName(refBase(s.Ref))
	case s.Type == "array":
		return "[]" + goFieldType(s.Items)
	case s.Type == "integer":
		return "int"
	case s.Type == "number":
		return "float64"
	case s.Type == "boolean":
		return "bool"
	default:
		return "string"
	}
}

// toTSType renders a TypeScript type.
func toTSType(s *schema) string {
	switch {
	case s.Type == "object" || len(s.Properties) > 0:
		var b bytes.Buffer
		b.WriteString("{\n")
		keys := make([]string, 0, len(s.Properties))
		for k := range s.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			prop := s.Properties[k]
			optional := ""
			if !isRequired(k, s) {
				optional = "?"
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", k, optional, tsFieldType(prop)))
		}
		b.WriteString("}")
		return b.String()
	case s.Ref != "":
		return toTSName(refBase(s.Ref))
	case s.Type == "array":
		return tsFieldType(s.Items) + "[]"
	case s.Type == "integer", s.Type == "number":
		return "number"
	case s.Type == "boolean":
		return "boolean"
	default:
		if len(s.Enum) > 0 {
			return "string"
		}
		return "string"
	}
}

func tsFieldType(s *schema) string {
	switch {
	case s.Ref != "":
		return toTSName(refBase(s.Ref))
	case s.Type == "array":
		return tsFieldType(s.Items) + "[]"
	case s.Type == "integer", s.Type == "number":
		return "number"
	case s.Type == "boolean":
		return "boolean"
	default:
		return "string"
	}
}

func refBase(ref string) string {
	parts := strings.Split(ref, "/")
	return parts[len(parts)-1]
}

func toGoName(s string) string {
	// snake_case -> PascalCase.
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	out := b.String()
	if out == "" {
		return "Empty"
	}
	return out
}

func toTSName(s string) string {
	return toGoName(s)
}

// isRequired reports whether a property is in the (unused here) required list.
// The generator does not carry required arrays; properties are emitted
// omitempty in Go and optional in TS by default for forward compatibility.
func isRequired(_ string, _ *schema) bool { return false }

func docLine(s string) string {
	if s == "" {
		return ""
	}
	return strings.ReplaceAll(s, "\n", " ")
}
