// Code generated by tools/schema-gen. DO NOT EDIT.
// Source of truth: packages/*/schema (ADR-002).

export type BackendNode = {
  active?: boolean;
  host?: string;
  id?: Ulid;
  port?: number;
  weight?: number;
};

export type BackendPool = {
  application_id?: Ulid;
  health_monitor?: HealthMonitor;
  id?: Ulid;
  lb_algorithm?: string;
  name?: string;
  nodes?: BackendNode[];
};

export type HealthMonitor = {
  fail_threshold?: number;
  http_expected_status?: number[];
  http_path?: string;
  interval_ms?: number;
  pass_threshold?: number;
  timeout_ms?: number;
  type?: string;
};

export type Route = {
  backend_pool_id?: Ulid;
  id?: Ulid;
  match?: string;
  path?: string;
  priority?: number;
};

export type Timestamp = string;

export type TlsProfile = {
  certificate_ref?: string;
  enabled?: boolean;
  min_version?: string;
  protocols?: string[];
};

export type Ulid = string;

export type VirtualServer = {
  default_backend_pool_id?: Ulid;
  id?: Ulid;
  limits?: string;
  listen_addr?: string;
  listen_port?: number;
  name?: string;
  routes?: Route[];
  tls?: TlsProfile;
};

export type Client = {
  forwarded_for?: string;
  ip?: string;
  port?: number;
};

export type Decision = {
  action?: string;
  reason?: string;
};

export type Request = {
  body_size?: number;
  content_type?: string;
  headers_count?: number;
  host?: string;
  http_version?: string;
  method?: string;
  path?: string;
  query?: string;
};

export type Response = {
  backend_node?: string;
  bytes?: number;
  latency_ms?: number;
  status?: number;
};

